
services:
  postgres:
    image: postgres:16
    container_name: sgp-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgp-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo '🚀 Iniciando API NestJS em produção...' &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node dist/main.js
      "

volumes:
  postgres_data:
