version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: sgp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sgp-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: sgp-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/sgp-db?schema=public"
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo 'Esperando banco ficar pronto...' &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node dist/main.js
      "

volumes:
  postgres_data:
