version: '3.9'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nest-network


  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge
